os: osx
osx_image: xcode10.2

language: node_js

node_js:
  - node
  - lts/*

cache:
  directories:
    - node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"

env:
  NODE_ENV='travis'

script:
  - npm run build
